function buildCSS() {
  var c = [
    '*{box-sizing:border-box;margin:0;padding:0}',
    ':root{--p:#7c3aed;--pd:#6d28d9;--bg:#f5f5f7;--card:#fff;--text:#1a1a1a;--text2:#888;--border:#e5e5e5}',
    'body{font-family:-apple-system,sans-serif;background:var(--bg);color:var(--text);line-height:1.5;min-height:100vh;display:flex;flex-direction:column}',
    'a{text-decoration:none;color:inherit}',
    '.wrap{max-width:1100px;margin:0 auto;padding:0 16px;width:100%}',
    'header{background:var(--p);color:#fff;padding:12px 0;position:sticky;top:0;z-index:100;box-shadow:0 2px 8px rgba(0,0,0,.1)}',
    'header .wrap{display:flex;align-items:center;gap:14px;flex-wrap:wrap}',
    '.logo{font-size:24px;font-weight:800}',
    '.logo span{color:#e9d5ff}',
    'header input.q{flex:1;padding:9px 12px;border:0;border-radius:6px;min-width:150px;max-width:400px}',
    '.act{padding:8px 13px;border-radius:6px;font-weight:600;background:rgba(255,255,255,.15);cursor:pointer;border:0;color:#fff;font-size:13px;display:inline-block}',
    '.act:hover{background:rgba(255,255,255,.25)}',
    '.badge{background:#dc2626;color:#fff;font-size:10px;padding:1px 6px;border-radius:999px;margin-left:4px}',
    'main{flex:1;padding:20px 0 60px}',
    'h1.page{font-size:22px;margin-bottom:16px;font-weight:800}',
    'h2.sec{font-size:18px;margin:20px 0 14px;font-weight:800}',
    '.cat-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:14px;margin-bottom:24px}',
    '.cat-card{background:var(--card);border-radius:12px;padding:20px;border:1px solid var(--border);display:flex;gap:14px;align-items:center;transition:.2s}',
    '.cat-card:hover{transform:translateY(-3px);box-shadow:0 8px 24px rgba(0,0,0,.08)}',
    '.cat-icon{font-size:14px;font-weight:800;color:var(--p);background:#ede9fe;padding:10px 12px;border-radius:8px}',
    '.cat-name{font-weight:800;font-size:15px}',
    '.cat-desc{font-size:12px;color:var(--text2)}',
    '.cat-count{font-size:11px;color:var(--p);font-weight:700;margin-top:4px}',
    '.topic-list{display:flex;flex-direction:column;gap:8px}',
    '.topic{background:var(--card);border-radius:10px;border:1px solid var(--border);padding:14px;display:flex;gap:14px;align-items:center}',
    '.topic:hover{border-color:var(--p)}',
    '.topic-vote{text-align:center;min-width:50px}',
    '.vote-btn{background:transparent;border:1px solid var(--border);width:32px;height:32px;border-radius:6px;cursor:pointer;color:var(--text2);font-size:14px;font-weight:700}',
    '.vote-btn.on-up{background:var(--p);border-color:var(--p);color:#fff}',
    '.vote-btn.on-down{background:#dc2626;border-color:#dc2626;color:#fff}',
    '.vote-count{font-weight:800;margin:6px 0}',
    '.topic-info{flex:1;min-width:0}',
    '.topic-title{font-weight:700;font-size:15px}',
    '.topic-title:hover{color:var(--p)}',
    '.topic-meta{font-size:12px;color:var(--text2);margin-top:5px;display:flex;gap:10px;flex-wrap:wrap}',
    '.tag{background:#ede9fe;color:var(--p);padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700}',
    '.prefix{background:#fef3c7;color:#92400e;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;margin-right:6px}',
    '.topic-avatar{width:40px;height:40px;border-radius:50%;background:var(--p);color:#fff;display:grid;place-items:center;font-weight:800;font-size:15px}',
    '.topic-header{background:var(--card);border-radius:12px;padding:22px;border:1px solid var(--border);margin-bottom:16px}',
    '.topic-body{font-size:15px;line-height:1.7;margin-top:14px;padding-top:14px;border-top:1px solid #f0f0f0;white-space:pre-wrap}',
    '.post{background:var(--card);border-radius:10px;border:1px solid var(--border);padding:16px;margin-bottom:10px;display:flex;gap:14px}',
    '.post-content{flex:1;min-width:0}',
    '.post-head{font-size:12px;color:var(--text2);margin-bottom:8px;display:flex;gap:8px;align-items:center;flex-wrap:wrap}',
    '.post-body{font-size:14px;line-height:1.65;white-space:pre-wrap}',
    '.post.nested{margin-left:40px;border-left:3px solid var(--p)}',
    '.btn{background:var(--p);color:#fff;border:0;border-radius:6px;padding:11px 22px;font-weight:700;cursor:pointer;display:inline-block;text-align:center;font-size:14px}',
    '.btn:hover{background:var(--pd)}',
    '.btn.full{width:100%;padding:13px}',
    '.btn.gray{background:#eee;color:#444}',
    '.btn.red{background:#dc2626}',
    '.btn.sm{padding:6px 12px;font-size:12px}',
    '.form-box{max-width:420px;margin:40px auto;background:var(--card);border-radius:12px;padding:32px;border:1px solid var(--border)}',
    '.form-box h1{font-size:22px;margin-bottom:6px}',
    '.field{margin-bottom:14px}',
    '.field label{display:block;font-size:12px;font-weight:700;color:#666;margin-bottom:6px;text-transform:uppercase}',
    '.field input,.field textarea,.field select{width:100%;padding:11px 13px;border:1px solid #ddd;border-radius:6px;font-size:14px;outline:0;font-family:inherit}',
    '.field textarea{resize:vertical;min-height:100px}',
    '.panel{background:var(--card);border-radius:10px;border:1px solid var(--border);padding:18px}',
    '.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:14px;margin-bottom:20px}',
    '.stat{background:var(--card);border:1px solid var(--border);border-radius:10px;padding:16px}',
    '.stat b{display:block;font-size:24px;color:var(--p)}',
    '.stat span{font-size:12px;color:var(--text2);text-transform:uppercase}',
    '.tabs{display:flex;gap:4px;border-bottom:2px solid #f0f0f0;margin-bottom:20px;flex-wrap:wrap}',
    '.tab{padding:10px 16px;font-weight:700;color:#888;border-bottom:3px solid transparent}',
    '.tab.on{color:var(--p);border-bottom-color:var(--p)}',
    'table{width:100%;border-collapse:collapse}',
    'th{text-align:left;padding:10px;font-size:11px;text-transform:uppercase;color:#888;border-bottom:2px solid #f0f0f0}',
    'td{padding:10px;border-bottom:1px solid #f5f5f5}',
    '.alert{padding:12px 16px;border-radius:8px;font-weight:600;margin-bottom:16px;font-size:14px}',
    '.alert.ok{background:#dcfce7;color:#15803d}',
    '.alert.err{background:#fee2e2;color:#b91c1c}',
    '.alert.info{background:#dbeafe;color:#1d4ed8}',
    '.crumb{font-size:13px;color:var(--text2);margin-bottom:12px}',
    '.crumb a:hover{color:var(--p)}',
    '.profile-head{background:var(--card);border-radius:12px;padding:24px;border:1px solid var(--border);margin-bottom:20px;display:flex;gap:20px;align-items:center;flex-wrap:wrap}',
    '.profile-avatar{width:90px;height:90px;border-radius:50%;background:var(--p);color:#fff;display:grid;place-items:center;font-weight:800;font-size:32px}',
    '.profile-stats{display:flex;gap:20px;margin-top:8px;font-size:13px;color:var(--text2)}',
    '.profile-stats b{color:var(--p);font-size:16px}',
    'footer{background:#1a1a1a;color:#aaa;padding:30px 0;text-align:center;font-size:12px;margin-top:auto}',
    'body.dark{--bg:#121212;--card:#1e1e1e;--text:#eee;--text2:#aaa;--border:#333}',
    'body.dark .post,body.dark .topic,body.dark .panel,body.dark .topic-header{background:#1e1e1e;border-color:#333}',
    'body.dark input,body.dark textarea,body.dark select{background:#2a2a2a;color:#eee;border-color:#333}',
    'body.dark .post-body,body.dark .topic-body{color:#ddd}',
    '.reactions{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}',
    '.reaction{padding:4px 10px;border-radius:999px;border:1px solid var(--border);background:var(--card);cursor:pointer;font-size:13px;display:inline-flex;gap:4px;align-items:center}',
    '.reaction:hover{border-color:var(--p)}',
    '.reaction.on{background:#ede9fe;border-color:var(--p);color:var(--p);font-weight:700}',
    '.reaction-count{font-size:11px;color:#666}',
    '.bookmark-btn{background:transparent;border:1px solid var(--border);padding:6px 12px;border-radius:6px;cursor:pointer;font-size:12px;font-weight:700;color:#888}',
    '.bookmark-btn.on{background:#fef3c7;border-color:#f59e0b;color:#92400e}',
    '.tag-cloud{display:flex;gap:8px;flex-wrap:wrap;padding:16px;background:var(--card);border-radius:10px;border:1px solid var(--border)}',
    '.tag-cloud a{padding:5px 12px;border-radius:999px;background:#ede9fe;color:var(--p);font-size:12px;font-weight:700}',
    '.tag-cloud a:hover{background:var(--p);color:#fff}',
    '.tag-cloud a.big{font-size:16px;padding:8px 18px}',
    '.tag-cloud a.mid{font-size:14px}',
    '.admin-ban{background:#dc2626;color:#fff;border:0;padding:5px 10px;border-radius:5px;font-size:12px;cursor:pointer;font-weight:700}',
    '@media(max-width:700px){.cat-grid{grid-template-columns:1fr 1fr}.topic{padding:10px}.topic-avatar{width:34px;height:34px;font-size:13px}.post.nested{margin-left:15px}.profile-head{flex-direction:column;text-align:center}}'
  ];
  return c.join('\n');
}
module.exports = { buildCSS: buildCSS };
